### ISSUE TITLE
Collections and subcription  with dot (.) in name fail ( Meteor ver 1.0.3.1

### ISSUE THREAD

**Issue by eportico** [percolatestudio/meteor-server-info#2]
MongoError: The dotted field 'sae.things' in 'info.counts.oplogObserveHandles.sae.things' is not valid for storage.
I20150130-11:52:30.409(1)?     at Object.Future.wait (/home/meteor/.meteor/packages/meteor-tool/.1.0.40.14f6fyl++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:326:15)
I20150130-11:52:30.409(1)?     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
I20150130-11:52:30.409(1)?     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:634:1)
I20150130-11:52:30.409(1)?     at Object.fields (packages/matb33:collection-hooks/update.js:75:1)
I20150130-11:52:30.409(1)?     at Object.collection.(anonymous function) [as update] (packages/matb33:collection-hooks/collection-hooks.js:99:1)
I20150130-11:52:30.409(1)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/mongo/collection.js:574:1)
I20150130-11:52:30.410(1)?     at [object Object].Mongo.Collection.upsert (packages/mongo/collection.js:608:1)
I20150130-11:52:30.410(1)?     at KeepAlive (app/server/helpers.js:16:13)
I20150130-11:52:30.410(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150130-11:52:30.410(1)?     at packages/meteor/timers.js:6:1

**Comment by zol** [comment]
This looks like a bug, thanks for reporting it @eportico .

**Comment by fgm** [comment]
Any chance you checked this on a more recent Meteor version ? I never find any dotted keys when using a recent (> 1.6) version for my NPM port ( https://github.com/fgm/meteor_server_info ).
